server:
  port: 8762
#
#server:
#  port: 8765
# springboot 启动选中allow paraller run 可启动两个服务
#
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411/
    # 可以指定监控数据的采样率
  sleuth:
      sampler:
        probability: 1

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://peer1:8761/eureka/
  instance:
    hostname: service-hi