server:
  port: 8762
#
#server:
#  port: 8765
# springboot 启动选中allow paraller run 可启动两个服务
#
spring:
  application:
    name: service-hi
  zipkin:
    enabled: true
    base-url: http://locahost:9411/
    locator:
      discovery:
        enabled: true
    sender:
      type: web
    sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://peer1:8761/eureka/
  instance:
    hostname: service-hi
