eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8767

spring:
  application:
    #工程名称
    name: service-hystrix-dashboard-turbine

turbine:
  combine-host-port: true
  #配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: service-ribbon,service-ribbon2
  #指定聚合哪些集群，多个使用”,”分割，默认为default。
  #可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  cluster-name-expression: metadata['cluster']
  aggregator:
    cluster-config: ribbon

  instanceUrlSuffix: /xxx/hystrix

