eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      cluster: ribbon
#server:
#  port: 8764
#spring:
#  application:
#    #工程名称
#    name: service-ribbon
server:
  port: 8765
spring:
  application:
    #工程名称
    name: service-ribbon2
