eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769
spring:
  application:
    name: service-zuul
  zipkin:
    enabled: true
    base-url: http://locahost:9411/
    locator:
      discovery:
        enabled: true
    sender:
      type: web
    sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
  retryable: true
#com.netflix.zuul.exception.ZuulException: Forwarding error
#ribbon请求超时添加一下部分
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 1000
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #默认为false,则只允许GET请求被重试
  OkToRetryOnAllOperations: true
  #最大自动重试下一个服务的次数
  MaxAutoRetriesNextServer: 0
  #某些响应状态码进行重试
  #retryableStatusCodes: 404,502
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000