spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3

server:
  port: 8768

eureka:
  instance:
    hostname: peer3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/