
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: up1
server:
  port: 8000
eureka:
  instance:
    hostname: up1
  client:
    serviceUrl:
      defaultZone: http://up2:8001/eureka/,http://up3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: up2
  client:
    serviceUrl:
      defaultZone: http://up1:8000/eureka/,http://up3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: up3
server:
  port: 8002
eureka:
  instance:
    hostname: up3
  client:
    serviceUrl:
      defaultZone: http://up1:8000/eureka/,http://up2:8001/eureka/
