
server:
  port: 8769

spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/